version: "3.8"
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61613
    depends_on:
      activemq:
        condition: service_healthy

  activemq:
    image: islandora/activemq:main
    container_name: activemq
    environment:
      - ACTIVEMQ_NAME=activemq
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
    ports:
      - 8161:8161
    volumes:
      - ./activemq/data:/data/activemq
      - ./activemq/log:/var/log/activem
    healthcheck:
      test: ["CMD", "sleep", "1"]
      interval: 5s
      retries: 0
